<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCharacterItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('equipment', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('character_id');
            $table->string('src', 100);
            $table->smallInteger('type');
            $table->integer('hp');
            $table->integer('xp');
            $table->integer('gold');
            $table->integer('price');
            $table->smallInteger('offset');
            $table->string('classes');
        });
        DB::table('equipment')->insert(
            [
                ['id' => '1', 'src' => 'boots-0_75d4eab23.png', 'offset' => '0', 'type' => '0', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'boots'],
                ['id' => '2', 'src' => 'boots-1_cf6b23.png', 'offset' => '1', 'type' => '0', 'character_id' => '1', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '150', 'classes' => 'boots'],
                ['id' => '3', 'src' => 'boots-2_cf69ab23.png', 'offset' => '2', 'type' => '0', 'character_id' => '1', 'hp' => '10', 'xp' => '0', 'gold' => '0', 'price' => '300', 'classes' => 'boots'],
                ['id' => '4', 'src' => 'boots-3_3f33afb.png', 'offset' => '3', 'type' => '0', 'character_id' => '1', 'hp' => '10', 'xp' => '5', 'gold' => '5', 'price' => '500', 'classes' => 'boots'],
                ['id' => '5', 'src' => 'armor-0_a6ab82e.png', 'offset' => '0', 'type' => '1', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'armor'],
                ['id' => '6', 'src' => 'armor-1_97456.png', 'offset' => '1', 'type' => '1', 'character_id' => '1', 'hp' => '10', 'xp' => '0', 'gold' => '0', 'price' => '300', 'classes' => 'armor'],
                ['id' => '7', 'src' => 'armor-2_0762db6a6a.png', 'offset' => '2', 'type' => '1', 'character_id' => '1', 'hp' => '15', 'xp' => '5', 'gold' => '5', 'price' => '600', 'classes' => 'armor'],
                ['id' => '8', 'src' => 'armor-3_af890fb23.png', 'offset' => '3', 'type' => '1', 'character_id' => '1', 'hp' => '20', 'xp' => '10', 'gold' => '10', 'price' => '900', 'classes' => 'armor'],
                ['id' => '9', 'src' => 'guantlets-0_97s4d56.png', 'offset' => '0', 'type' => '2', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'gauntlet1'],
                ['id' => '10', 'src' => 'guantlets-1_12s78a.png', 'offset' => '1', 'type' => '2', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '5', 'price' => '150', 'classes' => 'gauntlet1'],
                ['id' => '11', 'src' => 'guantlets-2_dc78a578.png', 'offset' => '2', 'type' => '2', 'character_id' => '1', 'hp' => '5', 'xp' => '5', 'gold' => '10', 'price' => '300', 'classes' => 'gauntlet1'],
                ['id' => '12', 'src' => 'guantlets-3_785a78f.png', 'offset' => '3', 'type' => '2', 'character_id' => '1', 'hp' => '5', 'xp' => '5', 'gold' => '15', 'price' => '600', 'classes' => 'gauntlet1'],
                ['id' => '13', 'src' => 'helmet-0_97456.png', 'offset' => '0', 'type' => '3', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'helmet'],
                ['id' => '14', 'src' => 'helmet-1_a6ab82e.png', 'offset' => '1', 'type' => '3', 'character_id' => '1', 'hp' => '0', 'xp' => '5', 'gold' => '0', 'price' => '200', 'classes' => 'helmet'],
                ['id' => '15', 'src' => 'helmet-2_97s4d56.png', 'offset' => '2', 'type' => '3', 'character_id' => '1', 'hp' => '5', 'xp' => '10', 'gold' => '5', 'price' => '400', 'classes' => 'helmet'],
                ['id' => '16', 'src' => 'helmet-3_f6a0823.png', 'offset' => '3', 'type' => '3', 'character_id' => '1', 'hp' => '10', 'xp' => '15', 'gold' => '10', 'price' => '500', 'classes' => 'helmet'],
                ['id' => '17', 'src' => 'shield-0_0762db6a6a.png', 'offset' => '0', 'type' => '4', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'shield'],
                ['id' => '18', 'src' => 'shield-1_dc78a578.png', 'offset' => '1', 'type' => '4', 'character_id' => '1', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '150', 'classes' => 'shield'],
                ['id' => '19', 'src' => 'shield-2_cf69ab23.png', 'offset' => '2', 'type' => '4', 'character_id' => '1', 'hp' => '15', 'xp' => '0', 'gold' => '0', 'price' => '300', 'classes' => 'shield'],
                ['id' => '20', 'src' => 'shield-3_a6ab82e.png', 'offset' => '3', 'type' => '4', 'character_id' => '1', 'hp' => '20', 'xp' => '10', 'gold' => '5', 'price' => '600', 'classes' => 'shield'],
                ['id' => '21', 'src' => 'sword-0_974536_char.png', 'offset' => '0', 'type' => '5', 'character_id' => '1', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'sword'],
                ['id' => '22', 'src' => 'sword-1_3f33afb_char.png', 'offset' => '1', 'type' => '5', 'character_id' => '1', 'hp' => '0', 'xp' => '5', 'gold' => '5', 'price' => '300', 'classes' => 'sword'],
                ['id' => '23', 'src' => 'sword-2_dc78a578_char.png', 'offset' => '2', 'type' => '5', 'character_id' => '1', 'hp' => '0', 'xp' => '10', 'gold' => '10', 'price' => '600', 'classes' => 'sword'],
                ['id' => '24', 'src' => 'sword-3_a6abe82e_char.png', 'offset' => '3', 'type' => '5', 'character_id' => '1', 'hp' => '5', 'xp' => '15', 'gold' => '15', 'price' => '900', 'classes' => 'sword'],
                ['id' => '25', 'src' => 'boots-archer-0_943837.png', 'offset' => '0', 'type' => '0', 'character_id' => '2', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'boots'],
                ['id' => '26', 'src' => 'boots-archer-1_0098721.png', 'offset' => '1', 'type' => '0', 'character_id' => '2', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '200', 'classes' => 'boots'],
                ['id' => '27', 'src' => 'boots-archer-2_6673907.png', 'offset' => '2', 'type' => '0', 'character_id' => '2', 'hp' => '5', 'xp' => '10', 'gold' => '5', 'price' => '400', 'classes' => 'boots'],
                ['id' => '28', 'src' => 'boots-archer-3_133928.png', 'offset' => '3', 'type' => '0', 'character_id' => '2', 'hp' => '10', 'xp' => '20', 'gold' => '10', 'price' => '600', 'classes' => 'boots'],
                ['id' => '29', 'src' => 'armor-archer-0_921afe2.png', 'offset' => '0', 'type' => '1', 'character_id' => '2', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'armor'],
                ['id' => '30', 'src' => 'armor-archer-1_aaf34e2d.png', 'offset' => '1', 'type' => '1', 'character_id' => '2', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '200', 'classes' => 'armor'],
                ['id' => '31', 'src' => 'armor-archer-2_feb4c503.png', 'offset' => '2', 'type' => '1', 'character_id' => '2', 'hp' => '10', 'xp' => '15', 'gold' => '5', 'price' => '400', 'classes' => 'armor'],
                ['id' => '32', 'src' => 'armor-archer-3_9a8ddd64.png', 'offset' => '3', 'type' => '1', 'character_id' => '2', 'hp' => '10', 'xp' => '20', 'gold' => '15', 'price' => '600', 'classes' => 'armor'],
                ['id' => '33', 'src' => 'helmet_archer_0-5ec62a.png', 'offset' => '0', 'type' => '3', 'character_id' => '2', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'helmet'],
                ['id' => '34', 'src' => 'helmet_archer_1-eff623a.png', 'offset' => '1', 'type' => '3', 'character_id' => '2', 'hp' => '0', 'xp' => '10', 'gold' => '0', 'price' => '400', 'classes' => 'helmet'],
                ['id' => '35', 'src' => 'helmet_archer_2-555afc3.png', 'offset' => '2', 'type' => '3', 'character_id' => '2', 'hp' => '5', 'xp' => '10', 'gold' => '5', 'price' => '800', 'classes' => 'helmet'],
                ['id' => '36', 'src' => 'helmet_archer_3-fa98340abc.png', 'offset' => '3', 'type' => '3', 'character_id' => '2', 'hp' => '10', 'xp' => '20', 'gold' => '10', 'price' => '1000', 'classes' => 'helmet'],
                ['id' => '37', 'src' => 'bow-0_ffb467.png', 'offset' => '0', 'type' => '5', 'character_id' => '2', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'bow'],
                ['id' => '38', 'src' => 'bow-1_05fc4dd3.png', 'offset' => '1', 'type' => '5', 'character_id' => '2', 'hp' => '0', 'xp' => '15', 'gold' => '5', 'price' => '700', 'classes' => 'bow'],
                ['id' => '39', 'src' => 'bow-2_fcafb.png', 'offset' => '2', 'type' => '5', 'character_id' => '2', 'hp' => '5', 'xp' => '15', 'gold' => '10', 'price' => '1400', 'classes' => 'bow'],
                ['id' => '40', 'src' => 'bow-3_34abc56.png', 'offset' => '3', 'type' => '5', 'character_id' => '2', 'hp' => '10', 'xp' => '20', 'gold' => '15', 'price' => '2000', 'classes' => 'bow'],
                ['id' => '41', 'src' => 'archer_gauntlets.png', 'offset' => '0', 'type' => '2', 'character_id' => '2', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'gauntlet2'],
                ['id' => '42', 'src' => 'boots-mage-0_92084afc.png', 'offset' => '0', 'type' => '0', 'character_id' => '3', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'boots'],
                ['id' => '43', 'src' => 'boots-mage-1_a2f4c3.png', 'offset' => '1', 'type' => '0', 'character_id' => '3', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '200', 'classes' => 'boots'],
                ['id' => '44', 'src' => 'boots-mage-2_ffcac4.png', 'offset' => '2', 'type' => '0', 'character_id' => '3', 'hp' => '5', 'xp' => '0', 'gold' => '10', 'price' => '400', 'classes' => 'boots'],
                ['id' => '45', 'src' => 'boots-mage-4_0765ba2.png', 'offset' => '3', 'type' => '0', 'character_id' => '3', 'hp' => '10', 'xp' => '10', 'gold' => '20', 'price' => '600', 'classes' => 'boots'],
                ['id' => '46', 'src' => 'armor-mage-0_88623.png', 'offset' => '0', 'type' => '1', 'character_id' => '3', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'armor'],
                ['id' => '47', 'src' => 'armor-mage-1_76ab3c3.png', 'offset' => '1', 'type' => '1', 'character_id' => '3', 'hp' => '0', 'xp' => '0', 'gold' => '10', 'price' => '400', 'classes' => 'armor'],
                ['id' => '48', 'src' => 'armor-mage-2_998abe3.png', 'offset' => '2', 'type' => '1', 'character_id' => '3', 'hp' => '5', 'xp' => '5', 'gold' => '15', 'price' => '400', 'classes' => 'armor'],
                ['id' => '49', 'src' => 'armor-mage-3_ffc43.png', 'offset' => '3', 'type' => '1', 'character_id' => '3', 'hp' => '10', 'xp' => '15', 'gold' => '20', 'price' => '600', 'classes' => 'armor'],
                ['id' => '50', 'src' => 'mage_guantlets.png', 'offset' => '0', 'type' => '2', 'character_id' => '3', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'gauntlet2'],
                ['id' => '51', 'src' => 'helmet-mage-0_23453465.png', 'offset' => '0', 'type' => '3', 'character_id' => '3', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'helmet helmet-mage'],
                ['id' => '52', 'src' => 'helmet-mage-1_abc7392.png', 'offset' => '1', 'type' => '3', 'character_id' => '3', 'hp' => '0', 'xp' => '5', 'gold' => '0', 'price' => '200', 'classes' => 'helmet helmet-mage'],
                ['id' => '53', 'src' => 'helmet-mage-2_971bb2.png', 'offset' => '2', 'type' => '3', 'character_id' => '3', 'hp' => '10', 'xp' => '10', 'gold' => '10', 'price' => '800', 'classes' => 'helmet helmet-mage'],
                ['id' => '54', 'src' => 'helmet-mage-3_ab673.png', 'offset' => '3', 'type' => '3', 'character_id' => '3', 'hp' => '10', 'xp' => '10', 'gold' => '20', 'price' => '1000', 'classes' => 'helmet helmet-mage'],
                ['id' => '55', 'src' => 'staff-0_9827.png', 'offset' => '0', 'type' => '5', 'character_id' => '3', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'staff'],
                ['id' => '56', 'src' => 'staff-1_abcfff.png', 'offset' => '1', 'type' => '5', 'character_id' => '3', 'hp' => '5', 'xp' => '0', 'gold' => '15', 'price' => '700', 'classes' => 'staff'],
                ['id' => '57', 'src' => 'staff-2_ffa67dca.png', 'offset' => '2', 'type' => '5', 'character_id' => '3', 'hp' => '5', 'xp' => '10', 'gold' => '15', 'price' => '1400', 'classes' => 'staff'],
                ['id' => '58', 'src' => 'staff-3_43d2cfe.png', 'offset' => '3', 'type' => '5', 'character_id' => '3', 'hp' => '10', 'xp' => '15', 'gold' => '20', 'price' => '2000', 'classes' => 'staff'],
                ['id' => '59', 'src' => 'robots/robot1_legs.png', 'offset' => '0', 'type' => '0', 'character_id' => '4', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'bootsRobot1'],
                ['id' => '60', 'src' => 'robots/robot1_eq1_legs.png', 'offset' => '1', 'type' => '0', 'character_id' => '4', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '200', 'classes' => 'bootsRobot1'],
                ['id' => '61', 'src' => 'robots/robot1_eq2_legs.png', 'offset' => '2', 'type' => '0', 'character_id' => '4', 'hp' => '5', 'xp' => '10', 'gold' => '5', 'price' => '400', 'classes' => 'bootsRobot1'],
                ['id' => '62', 'src' => 'robots/robot1_eq3_legs.png', 'offset' => '3', 'type' => '0', 'character_id' => '4', 'hp' => '10', 'xp' => '20', 'gold' => '10', 'price' => '600', 'classes' => 'bootsRobot1'],
                ['id' => '63', 'src' => 'robots/robot1_body.png', 'offset' => '0', 'type' => '1', 'character_id' => '4', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'armorRobot1'],
                ['id' => '64', 'src' => 'robots/robot1_eq1_body.png', 'offset' => '1', 'type' => '1', 'character_id' => '4', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '200', 'classes' => 'armorRobot1'],
                ['id' => '65', 'src' => 'robots/robot1_eq2_body.png', 'offset' => '2', 'type' => '1', 'character_id' => '4', 'hp' => '10', 'xp' => '15', 'gold' => '5', 'price' => '400', 'classes' => 'armorRobot1'],
                ['id' => '66', 'src' => 'robots/robot1_eq3_body.png', 'offset' => '3', 'type' => '1', 'character_id' => '4', 'hp' => '10', 'xp' => '20', 'gold' => '15', 'price' => '800', 'classes' => 'armorRobot1'],
                ['id' => '67', 'src' => 'robots/robot1_bowtie.png', 'offset' => '0', 'type' => '2', 'character_id' => '4', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'bowTieRobot1'],
                ['id' => '68', 'src' => 'robots/robot1_eq1_bowtie.png', 'offset' => '1', 'type' => '2', 'character_id' => '4', 'hp' => '0', 'xp' => '10', 'gold' => '0', 'price' => '400', 'classes' => 'bowTieRobot1'],
                ['id' => '69', 'src' => 'robots/robot1_eq2_bowtie.png', 'offset' => '2', 'type' => '2', 'character_id' => '4', 'hp' => '5', 'xp' => '10', 'gold' => '5', 'price' => '800', 'classes' => 'bowTieRobot1'],
                ['id' => '70', 'src' => 'robots/robot1_eq3_bowtie.png', 'offset' => '3', 'type' => '2', 'character_id' => '4', 'hp' => '10', 'xp' => '20', 'gold' => '10', 'price' => '600', 'classes' => 'bowTieRobot1'],
                ['id' => '71', 'src' => 'robots/robot1_head.png', 'offset' => '0', 'type' => '3', 'character_id' => '4', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'helmet helmetRobot1'],
                ['id' => '72', 'src' => 'robots/robot1_eq1_head.png', 'offset' => '1', 'type' => '3', 'character_id' => '4', 'hp' => '0', 'xp' => '15', 'gold' => '5', 'price' => '700', 'classes' => 'helmet helmetRobot1'],
                ['id' => '73', 'src' => 'robots/robot1_eq2_head.png', 'offset' => '2', 'type' => '3', 'character_id' => '4', 'hp' => '5', 'xp' => '15', 'gold' => '10', 'price' => '1000', 'classes' => 'helmet helmetRobot1'],
                ['id' => '74', 'src' => 'robots/robot1_eq3_head.png', 'offset' => '3', 'type' => '3', 'character_id' => '4', 'hp' => '10', 'xp' => '20', 'gold' => '15', 'price' => '1800', 'classes' => 'helmet helmetRobot1'],
                ['id' => '75', 'src' => 'robots/robot1_gauntlet.png', 'offset' => '0', 'type' => '4', 'character_id' => '4', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'gauntletRobot1'],
                ['id' => '76', 'src' => 'robots/robot2_legs.png', 'offset' => '0', 'type' => '0', 'character_id' => '5', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'bootsRobot2'],
                ['id' => '77', 'src' => 'robots/robot2_eq1_legs.png', 'offset' => '1', 'type' => '0', 'character_id' => '5', 'hp' => '5', 'xp' => '0', 'gold' => '0', 'price' => '200', 'classes' => 'bootsRobot2'],
                ['id' => '78', 'src' => 'robots/robot2_eq2_legs.png', 'offset' => '2', 'type' => '0', 'character_id' => '5', 'hp' => '15', 'xp' => '0', 'gold' => '0', 'price' => '300', 'classes' => 'bootsRobot2'],
                ['id' => '79', 'src' => 'robots/robot2_eq3_legs.png', 'offset' => '3', 'type' => '0', 'character_id' => '5', 'hp' => '10', 'xp' => '5', 'gold' => '5', 'price' => '500', 'classes' => 'bootsRobot2'],
                ['id' => '80', 'src' => 'robots/robot2_body.png', 'offset' => '0', 'type' => '1', 'character_id' => '5', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'armorRobot2'],
                ['id' => '81', 'src' => 'robots/robot2_eq1_body.png', 'offset' => '1', 'type' => '1', 'character_id' => '5', 'hp' => '10', 'xp' => '0', 'gold' => '0', 'price' => '400', 'classes' => 'armorRobot2'],
                ['id' => '82', 'src' => 'robots/robot2_eq2_body.png', 'offset' => '2', 'type' => '1', 'character_id' => '5', 'hp' => '15', 'xp' => '5', 'gold' => '10', 'price' => '800', 'classes' => 'armorRobot2'],
                ['id' => '83', 'src' => 'robots/robot2_eq3_body.png', 'offset' => '3', 'type' => '1', 'character_id' => '5', 'hp' => '20', 'xp' => '10', 'gold' => '10', 'price' => '900', 'classes' => 'armorRobot2'],
                ['id' => '84', 'src' => 'robots/robot2_eyes.png', 'offset' => '0', 'type' => '2', 'character_id' => '5', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'bowTieRobot2'],
                ['id' => '85', 'src' => 'robots/robot2_eq1_eyes.png', 'offset' => '1', 'type' => '2', 'character_id' => '5', 'hp' => '5', 'xp' => '0', 'gold' => '5', 'price' => '400', 'classes' => 'bowTieRobot2'],
                ['id' => '86', 'src' => 'robots/robot2_eq2_eyes.png', 'offset' => '2', 'type' => '2', 'character_id' => '5', 'hp' => '5', 'xp' => '10', 'gold' => '5', 'price' => '400', 'classes' => 'bowTieRobot2'],
                ['id' => '87', 'src' => 'robots/robot2_eq3_eyes.png', 'offset' => '3', 'type' => '2', 'character_id' => '5', 'hp' => '15', 'xp' => '15', 'gold' => '15', 'price' => '900', 'classes' => 'bowTieRobot2'],
                ['id' => '88', 'src' => 'robots/robot2_head.png', 'offset' => '0', 'type' => '3', 'character_id' => '5', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'helmet helmetRobot2'],
                ['id' => '89', 'src' => 'robots/robot2_eq1_head.png', 'offset' => '1', 'type' => '3', 'character_id' => '5', 'hp' => '0', 'xp' => '5', 'gold' => '0', 'price' => '200', 'classes' => 'helmet helmetRobot2'],
                ['id' => '90', 'src' => 'robots/robot2_eq2_head.png', 'offset' => '2', 'type' => '3', 'character_id' => '5', 'hp' => '5', 'xp' => '5', 'gold' => '5', 'price' => '300', 'classes' => 'helmet helmetRobot2'],
                ['id' => '91', 'src' => 'robots/robot2_eq3_head.png', 'offset' => '3', 'type' => '3', 'character_id' => '5', 'hp' => '15', 'xp' => '15', 'gold' => '10', 'price' => '900', 'classes' => 'helmet helmetRobot2'],
                ['id' => '92', 'src' => 'robots/robot2_arms.png', 'offset' => '0', 'type' => '4', 'character_id' => '5', 'hp' => '0', 'xp' => '0', 'gold' => '0', 'price' => '0', 'classes' => 'gauntletRobot2 armorRobot2'],
                ['id' => '93', 'src' => 'robots/robot2_eq1_arms.png', 'offset' => '1', 'type' => '4', 'character_id' => '5', 'hp' => '0', 'xp' => '5', 'gold' => '5', 'price' => '300', 'classes' => 'gauntletRobot2 armorRobot2'],
                ['id' => '94', 'src' => 'robots/robot2_eq2_arms.png', 'offset' => '2', 'type' => '4', 'character_id' => '5', 'hp' => '10', 'xp' => '10', 'gold' => '10', 'price' => '800', 'classes' => 'gauntletRobot2 armorRobot2'],
                ['id' => '95', 'src' => 'robots/robot2_eq3_arms.png', 'offset' => '3', 'type' => '4', 'character_id' => '5', 'hp' => '10', 'xp' => '5', 'gold' => '15', 'price' => '600', 'classes' => 'gauntletRobot2 armorRobot2'],
                ['id' => '96','src' => 'robots/robot3_legs.png', 'offset' => '0', 'type' => '0','character_id' => '6','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'bootsRobot3'],
                ['id' => '97','src' => 'robots/robot3_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '6','hp' => '5','xp' => '0','gold' => '0','price' => '200','classes' => 'bootsRobot3'],
                ['id' => '98','src' => 'robots/robot3_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '6','hp' => '5','xp' => '0','gold' => '10','price' => '400','classes' => 'bootsRobot3'],
                ['id' => '99','src' => 'robots/robot3_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '6','hp' => '10','xp' => '10','gold' => '20','price' => '600','classes' => 'bootsRobot3'],
                ['id' => '100','src' => 'robots/robot3_body.png', 'offset' => '0', 'type' => '1','character_id' => '6','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'armorRobot3'],
                ['id' => '101','src' => 'robots/robot3_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '6','hp' => '0','xp' => '0','gold' => '10','price' => '400','classes' => 'armorRobot3'],
                ['id' => '102','src' => 'robots/robot3_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '6','hp' => '5','xp' => '5','gold' => '15','price' => '400','classes' => 'armorRobot3'],
                ['id' => '103','src' => 'robots/robot3_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '6','hp' => '10','xp' => '15','gold' => '20','price' => '800','classes' => 'armorRobot3'],
                ['id' => '108','src' => 'robots/robot3_head.png', 'offset' => '0', 'type' => '3','character_id' => '6','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'helmet helmetRobot3'],
                ['id' => '109','src' => 'robots/robot3_eq1_head.png', 'offset' => '1', 'type' => '3','character_id' => '6','hp' => '0','xp' => '5','gold' => '0','price' => '200','classes' => 'helmet helmetRobot3'],
                ['id' => '110','src' => 'robots/robot3_eq2_head.png', 'offset' => '2', 'type' => '3','character_id' => '6','hp' => '10','xp' => '10','gold' => '10','price' => '800','classes' => 'helmet helmetRobot3'],
                ['id' => '111','src' => 'robots/robot3_eq3_head.png', 'offset' => '3', 'type' => '3','character_id' => '6','hp' => '10','xp' => '10','gold' => '20','price' => '600','classes' => 'helmet helmetRobot3'],
                ['id' => '112','src' => 'robots/robot3_arms.png', 'offset' => '0', 'type' => '4','character_id' => '6','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'gauntletRobot3 armorRobot3'],
                ['id' => '113','src' => 'robots/robot3_eq1_arms.png', 'offset' => '1', 'type' => '4','character_id' => '6','hp' => '5','xp' => '0','gold' => '15','price' => '700','classes' => 'gauntletRobot3 armorRobot3'],
                ['id' => '114','src' => 'robots/robot3_eq2_arms.png', 'offset' => '2', 'type' => '4','character_id' => '6','hp' => '5','xp' => '10','gold' => '15','price' => '1000','classes' => 'gauntletRobot3 armorRobot3'],
                ['id' => '115','src' => 'robots/robot3_eq3_arms.png', 'offset' => '3', 'type' => '4','character_id' => '6','hp' => '10','xp' => '15','gold' => '20','price' => '1800','classes' => 'gauntletRobot3 armorRobot3'],
                ['id' => '140','src' => 'superheros/sh0_legs.png', 'offset' => '0', 'type' => '0','character_id' => '7','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute legs-sh1'],
                ['id' => '141','src' => 'superheros/sh0_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '7','hp' => '5','xp' => '0','gold' => '0','price' => '200','classes' => 'fly is-absolute legs-sh1'],
                ['id' => '142','src' => 'superheros/sh0_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '7','hp' => '5','xp' => '0','gold' => '10','price' => '400','classes' => 'fly is-absolute legs-sh1'],
                ['id' => '143','src' => 'superheros/sh0_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '7','hp' => '10','xp' => '10','gold' => '20','price' => '600','classes' => 'fly is-absolute legs-sh1'],
                ['id' => '144','src' => 'superheros/sh0_body.png', 'offset' => '0', 'type' => '1','character_id' => '7','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute body-sh1 lastPart'],
                ['id' => '145','src' => 'superheros/sh0_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '7','hp' => '0','xp' => '0','gold' => '10','price' => '400','classes' => 'fly is-absolute body-sh1 lastPart'],
                ['id' => '146','src' => 'superheros/sh0_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '7','hp' => '5','xp' => '5','gold' => '15','price' => '400','classes' => 'fly is-absolute body-sh1 lastPart'],
                ['id' => '147','src' => 'superheros/sh0_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '7','hp' => '10','xp' => '15','gold' => '20','price' => '800','classes' => 'fly is-absolute body-sh1 lastPart'],
                ['id' => '148','src' => 'superheros/sh0_head.png', 'offset' => '0', 'type' => '3','character_id' => '7','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute head-sh1'],
                ['id' => '149','src' => 'superheros/sh0_eq1_head.png', 'offset' => '1', 'type' => '3','character_id' => '7','hp' => '0','xp' => '5','gold' => '0','price' => '200','classes' => 'fly is-absolute head-sh1'],
                ['id' => '150','src' => 'superheros/sh0_eq2_head.png', 'offset' => '2', 'type' => '3','character_id' => '7','hp' => '10','xp' => '10','gold' => '10','price' => '800','classes' => 'fly is-absolute head-sh1'],
                ['id' => '151','src' => 'superheros/sh0_eq3_head.png', 'offset' => '3', 'type' => '3','character_id' => '7','hp' => '10','xp' => '10','gold' => '20','price' => '600','classes' => 'fly is-absolute head-sh1'],
                ['id' => '152','src' => 'superheros/sh0_arms.png', 'offset' => '0', 'type' => '4','character_id' => '7','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute arms-sh1 backPart'],
                ['id' => '153','src' => 'superheros/sh0_eq1_arms.png', 'offset' => '1', 'type' => '4','character_id' => '7','hp' => '5','xp' => '0','gold' => '15','price' => '700','classes' => 'fly is-absolute arms-sh1 backPart'],
                ['id' => '154','src' => 'superheros/sh0_eq2_arms.png', 'offset' => '2', 'type' => '4','character_id' => '7','hp' => '5','xp' => '10','gold' => '15','price' => '1000','classes' => 'fly is-absolute arms-sh1 backPart'],
                ['id' => '155','src' => 'superheros/sh0_eq3_arms.png', 'offset' => '3', 'type' => '4','character_id' => '7','hp' => '10','xp' => '15','gold' => '20','price' => '1800','classes' => 'fly is-absolute arms-sh1 backPart'],
                ['id' => '160','src' => 'superheros/sh1_legs.png', 'offset' => '0', 'type' => '0','character_id' => '8','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute legs-sh2'],
                ['id' => '161','src' => 'superheros/sh1_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '8','hp' => '0','xp' => '0','gold' => '5','price' => '200','classes' => 'fly is-absolute legs-sh2'],
                ['id' => '162','src' => 'superheros/sh1_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '8','hp' => '10','xp' => '0','gold' => '5','price' => '400','classes' => 'fly is-absolute legs-sh2'],
                ['id' => '163','src' => 'superheros/sh1_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '8','hp' => '20','xp' => '10','gold' => '10','price' => '600','classes' => 'fly is-absolute legs-sh2'],
                ['id' => '164','src' => 'superheros/sh1_body.png', 'offset' => '0', 'type' => '1','character_id' => '8','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute body-sh2 lastPart'],
                ['id' => '165','src' => 'superheros/sh1_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '8','hp' => '10','xp' => '0','gold' => '0','price' => '400','classes' => 'fly is-absolute body-sh2 lastPart'],
                ['id' => '166','src' => 'superheros/sh1_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '8','hp' => '15','xp' => '5','gold' => '5','price' => '400','classes' => 'fly is-absolute body-sh2 lastPart'],
                ['id' => '167','src' => 'superheros/sh1_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '8','hp' => '20','xp' => '15','gold' => '10','price' => '800','classes' => 'fly is-absolute body-sh2 lastPart'],
                ['id' => '168','src' => 'superheros/sh1_head.png', 'offset' => '0', 'type' => '3','character_id' => '8','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute head-sh2'],
                ['id' => '169','src' => 'superheros/sh1_eq1_head.png', 'offset' => '1', 'type' => '3','character_id' => '8','hp' => '0','xp' => '5','gold' => '0','price' => '200','classes' => 'fly is-absolute head-sh2'],
                ['id' => '170','src' => 'superheros/sh1_eq2_head.png', 'offset' => '2', 'type' => '3','character_id' => '8','hp' => '10','xp' => '10','gold' => '10','price' => '800','classes' => 'fly is-absolute head-sh2'],
                ['id' => '171','src' => 'superheros/sh1_eq3_head.png', 'offset' => '3', 'type' => '3','character_id' => '8','hp' => '20','xp' => '10','gold' => '10','price' => '600','classes' => 'fly is-absolute head-sh2'],
                ['id' => '172','src' => 'superheros/sh1_amulet.png', 'offset' => '0', 'type' => '4','character_id' => '8','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute arms-sh2 backPart'],
                ['id' => '173','src' => 'superheros/sh1_eq1_amulet.png', 'offset' => '1', 'type' => '4','character_id' => '8','hp' => '15','xp' => '0','gold' => '5','price' => '700','classes' => 'fly is-absolute arms-sh2 backPart'],
                ['id' => '174','src' => 'superheros/sh1_eq2_amulet.png', 'offset' => '2', 'type' => '4','character_id' => '8','hp' => '15','xp' => '10','gold' => '5','price' => '1000','classes' => 'fly is-absolute arms-sh2 backPart'],
                ['id' => '175','src' => 'superheros/sh1_eq3_amulet.png', 'offset' => '3', 'type' => '4','character_id' => '8','hp' => '20','xp' => '15','gold' => '10','price' => '1800','classes' => 'fly is-absolute arms-sh2 backPart'],
                ['id' => '180','src' => 'superheros/sh2_legs.png', 'offset' => '0', 'type' => '0','character_id' => '9','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute legs-sh3'],
                ['id' => '181','src' => 'superheros/sh2_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '9','hp' => '5','xp' => '0','gold' => '0','price' => '200','classes' => 'fly is-absolute legs-sh3'],
                ['id' => '182','src' => 'superheros/sh2_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '9','hp' => '5','xp' => '10','gold' => '0','price' => '400','classes' => 'fly is-absolute legs-sh3'],
                ['id' => '183','src' => 'superheros/sh2_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '9','hp' => '10','xp' => '20','gold' => '10','price' => '600','classes' => 'fly is-absolute legs-sh3'],
                ['id' => '184','src' => 'superheros/sh2_body.png', 'offset' => '0', 'type' => '1','character_id' => '9','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute body-sh3 lastPart'],
                ['id' => '185','src' => 'superheros/sh2_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '9','hp' => '0','xp' => '10','gold' => '0','price' => '400','classes' => 'fly is-absolute body-sh3 lastPart'],
                ['id' => '186','src' => 'superheros/sh2_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '9','hp' => '5','xp' => '15','gold' => '5','price' => '400','classes' => 'fly is-absolute body-sh3 lastPart'],
                ['id' => '187','src' => 'superheros/sh2_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '9','hp' => '15','xp' => '10','gold' => '20','price' => '800','classes' => 'fly is-absolute body-sh3 lastPart'],
                ['id' => '188','src' => 'superheros/sh2_head.png', 'offset' => '0', 'type' => '3','character_id' => '9','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute head-sh3'],
                ['id' => '189','src' => 'superheros/sh2_eq1_head.png', 'offset' => '1', 'type' => '3','character_id' => '9','hp' => '0','xp' => '0','gold' => '5','price' => '200','classes' => 'fly is-absolute head-sh3'],
                ['id' => '190','src' => 'superheros/sh2_eq2_head.png', 'offset' => '2', 'type' => '3','character_id' => '9','hp' => '10','xp' => '10','gold' => '10','price' => '800','classes' => 'fly is-absolute head-sh3'],
                ['id' => '191','src' => 'superheros/sh2_eq3_head.png', 'offset' => '3', 'type' => '3','character_id' => '9','hp' => '10','xp' => '20','gold' => '10','price' => '600','classes' => 'fly is-absolute head-sh3'],
                ['id' => '192','src' => 'superheros/sh2_arms.png', 'offset' => '0', 'type' => '4','character_id' => '9','hp' => '0','xp' => '0','gold' => '0','price' => '0','classes' => 'fly is-absolute arms-sh3 backPart'],
                ['id' => '193','src' => 'superheros/sh2_eq1_arms.png', 'offset' => '1', 'type' => '4','character_id' => '9','hp' => '5','xp' => '15','gold' => '0','price' => '700','classes' => 'fly is-absolute arms-sh3 backPart'],
                ['id' => '194','src' => 'superheros/sh2_eq2_arms.png', 'offset' => '2', 'type' => '4','character_id' => '9','hp' => '5','xp' => '15','gold' => '10','price' => '1000','classes' => 'fly is-absolute arms-sh3 backPart'],
                ['id' => '195','src' => 'superheros/sh2_eq3_arms.png', 'offset' => '3', 'type' => '4','character_id' => '9','hp' => '10','xp' => '20','gold' => '15','price' => '1800','classes' => 'fly is-absolute arms-sh3 backPart'],
            
                ['id' => '200','src' => 'pirateanimals/seal_tail.png', 'offset' => '0', 'type' => '0','character_id' => '10','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute tail-1'],
                ['id' => '201','src' => 'pirateanimals/seal_eq1_tail.png', 'offset' => '1', 'type' => '0','character_id' => '10','hp' => '5','xp' => '0','gold' => '5','price' => '400', 'classes' => 'is-absolute tail-1'],
                ['id' => '202','src' => 'pirateanimals/seal_eq2_tail.png', 'offset' => '2', 'type' => '0','character_id' => '10','hp' => '10','xp' => '5','gold' => '15','price' => '1000', 'classes' => 'is-absolute tail-1'],
                ['id' => '203','src' => 'pirateanimals/seal_eq3_tail.png', 'offset' => '3', 'type' => '0','character_id' => '10','hp' => '20','xp' => '15','gold' => '10','price' => '800', 'classes' => 'is-absolute tail-1'],
                ['id' => '204','src' => 'pirateanimals/seal_body.png', 'offset' => '0', 'type' => '1','character_id' => '10','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute body-1'],
                ['id' => '205','src' => 'pirateanimals/seal_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '10','hp' => '5','xp' => '0','gold' => '15','price' => '700', 'classes' => 'is-absolute body-1'],
                ['id' => '206','src' => 'pirateanimals/seal_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '10','hp' => '5','xp' => '10','gold' => '15','price' => '800', 'classes' => 'is-absolute body-1'],
                ['id' => '207','src' => 'pirateanimals/seal_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '10','hp' => '20','xp' => '15','gold' => '10','price' => '1200', 'classes' => 'is-absolute body-1'],
                ['id' => '208','src' => 'pirateanimals/seal_head.png', 'offset' => '0', 'type' => '2','character_id' => '10','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute head-1 moveHeadUD'],
                ['id' => '209','src' => 'pirateanimals/seal_eq1_head.png', 'offset' => '1', 'type' => '2','character_id' => '10','hp' => '0','xp' => '5','gold' => '5','price' => '400', 'classes' => 'is-absolute head-1 moveHeadUD'],
                ['id' => '210','src' => 'pirateanimals/seal_eq2_head.png', 'offset' => '2', 'type' => '2','character_id' => '10','hp' => '10','xp' => '10','gold' => '10','price' => '800', 'classes' => 'is-absolute head-1 moveHeadUD'],
                ['id' => '211','src' => 'pirateanimals/seal_eq3_head.png', 'offset' => '3', 'type' => '2','character_id' => '10','hp' => '40','xp' => '20','gold' => '20','price' => '1800', 'classes' => 'is-absolute head-1 moveHeadUD'],
                ['id' => '220','src' => 'pirateanimals/donkey_tail.png', 'offset' => '0', 'type' => '0','character_id' => '11','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute tail-2'],
                ['id' => '221','src' => 'pirateanimals/donkey_eq1_tail.png', 'offset' => '1', 'type' => '0','character_id' => '11','hp' => '5','xp' => '0','gold' => '5','price' => '400', 'classes' => 'is-absolute tail-2'],
                ['id' => '222','src' => 'pirateanimals/donkey_eq2_tail.png', 'offset' => '2', 'type' => '0','character_id' => '11','hp' => '15','xp' => '5','gold' => '10','price' => '1000', 'classes' => 'is-absolute tail-2'],
                ['id' => '223','src' => 'pirateanimals/donkey_eq3_tail.png', 'offset' => '3', 'type' => '0','character_id' => '11','hp' => '10','xp' => '15','gold' => '20','price' => '800', 'classes' => 'is-absolute tail-2'],
                ['id' => '224','src' => 'pirateanimals/donkey_body.png', 'offset' => '0', 'type' => '1','character_id' => '11','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute body-2'],
                ['id' => '225','src' => 'pirateanimals/donkey_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '11','hp' => '15','xp' => '0','gold' => '5','price' => '700', 'classes' => 'is-absolute body-2'],
                ['id' => '226','src' => 'pirateanimals/donkey_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '11','hp' => '15','xp' => '10','gold' => '5','price' => '800', 'classes' => 'is-absolute body-2'],
                ['id' => '227','src' => 'pirateanimals/donkey_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '11','hp' => '10','xp' => '15','gold' => '20','price' => '1200', 'classes' => 'is-absolute body-2'],
                ['id' => '228','src' => 'pirateanimals/donkey_head.png', 'offset' => '0', 'type' => '2','character_id' => '11','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute head-2 moveHeadUD'],
                ['id' => '229','src' => 'pirateanimals/donkey_eq1_head.png', 'offset' => '1', 'type' => '2','character_id' => '11','hp' => '5','xp' => '5','gold' => '0','price' => '400', 'classes' => 'is-absolute head-2 moveHeadUD'],
                ['id' => '230','src' => 'pirateanimals/donkey_eq2_head.png', 'offset' => '2', 'type' => '2','character_id' => '11','hp' => '10','xp' => '10','gold' => '10','price' => '800', 'classes' => 'is-absolute head-2 moveHeadUD'],
                ['id' => '231','src' => 'pirateanimals/donkey_eq3_head.png', 'offset' => '3', 'type' => '2','character_id' => '11','hp' => '20','xp' => '20','gold' => '40','price' => '1800', 'classes' => 'is-absolute head-2 moveHeadUD'],
                ['id' => '240','src' => 'pirateanimals/castor_legs.png', 'offset' => '0', 'type' => '0','character_id' => '12','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute legs-3'],
                ['id' => '241','src' => 'pirateanimals/castor_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '12','hp' => '0','xp' => '5','gold' => '5','price' => '400', 'classes' => 'is-absolute legs-3'],
                ['id' => '242','src' => 'pirateanimals/castor_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '12','hp' => '5','xp' => '10','gold' => '15','price' => '1000', 'classes' => 'is-absolute legs-3'],
                ['id' => '243','src' => 'pirateanimals/castor_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '12','hp' => '15','xp' => '20','gold' => '10','price' => '800', 'classes' => 'is-absolute legs-3'],
                ['id' => '244','src' => 'pirateanimals/castor_body.png', 'offset' => '0', 'type' => '1','character_id' => '12','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute body-3'],
                ['id' => '245','src' => 'pirateanimals/castor_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '12','hp' => '0','xp' => '5','gold' => '15','price' => '700', 'classes' => 'is-absolute body-3'],
                ['id' => '246','src' => 'pirateanimals/castor_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '12','hp' => '10','xp' => '5','gold' => '15','price' => '800', 'classes' => 'is-absolute body-3'],
                ['id' => '247','src' => 'pirateanimals/castor_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '12','hp' => '15','xp' => '20','gold' => '10','price' => '1200', 'classes' => 'is-absolute body-3'],
                ['id' => '248','src' => 'pirateanimals/castor_head.png', 'offset' => '0', 'type' => '2','character_id' => '12','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute head-3 moveHeadUD'],
                ['id' => '249','src' => 'pirateanimals/castor_eq1_head.png', 'offset' => '1', 'type' => '2','character_id' => '12','hp' => '5','xp' => '0','gold' => '5','price' => '400', 'classes' => 'is-absolute head-3 moveHeadUD'],
                ['id' => '250','src' => 'pirateanimals/castor_eq2_head.png', 'offset' => '2', 'type' => '2','character_id' => '12','hp' => '10','xp' => '10','gold' => '10','price' => '800', 'classes' => 'is-absolute head-3 moveHeadUD'],
                ['id' => '251','src' => 'pirateanimals/castor_eq3_head.png', 'offset' => '3', 'type' => '2','character_id' => '12','hp' => '20','xp' => '40','gold' => '20','price' => '1800', 'classes' => 'is-absolute head-3 moveHeadUD'],
                ['id' => '260','src' => 'pirateanimals/tiger_legs.png', 'offset' => '0', 'type' => '0','character_id' => '13','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute legs-4'],
                ['id' => '261','src' => 'pirateanimals/tiger_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '13','hp' => '5','xp' => '0','gold' => '5','price' => '400', 'classes' => 'is-absolute legs-4'],
                ['id' => '262','src' => 'pirateanimals/tiger_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '13','hp' => '10','xp' => '5','gold' => '15','price' => '1000', 'classes' => 'is-absolute legs-4'],
                ['id' => '263','src' => 'pirateanimals/tiger_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '13','hp' => '20','xp' => '15','gold' => '10','price' => '800', 'classes' => 'is-absolute legs-4'],
                ['id' => '264','src' => 'pirateanimals/tiger_body.png', 'offset' => '0', 'type' => '1','character_id' => '13','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute body-4'],
                ['id' => '265','src' => 'pirateanimals/tiger_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '13','hp' => '5','xp' => '0','gold' => '15','price' => '700', 'classes' => 'is-absolute body-4'],
                ['id' => '266','src' => 'pirateanimals/tiger_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '13','hp' => '5','xp' => '10','gold' => '15','price' => '800', 'classes' => 'is-absolute body-4'],
                ['id' => '267','src' => 'pirateanimals/tiger_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '13','hp' => '20','xp' => '15','gold' => '10','price' => '1200', 'classes' => 'is-absolute body-4'],
                ['id' => '268','src' => 'pirateanimals/tiger_head.png', 'offset' => '0', 'type' => '2','character_id' => '13','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute head-4 moveHeadUD'],
                ['id' => '269','src' => 'pirateanimals/tiger_eq1_head.png', 'offset' => '1', 'type' => '2','character_id' => '13','hp' => '0','xp' => '5','gold' => '5','price' => '400', 'classes' => 'is-absolute head-4 moveHeadUD'],
                ['id' => '270','src' => 'pirateanimals/tiger_eq2_head.png', 'offset' => '2', 'type' => '2','character_id' => '13','hp' => '10','xp' => '10','gold' => '10','price' => '800', 'classes' => 'is-absolute head-4 moveHeadUD'],
                ['id' => '271','src' => 'pirateanimals/tiger_eq3_head.png', 'offset' => '3', 'type' => '2','character_id' => '13','hp' => '40','xp' => '20','gold' => '20','price' => '1800', 'classes' => 'is-absolute head-4 moveHeadUD'],
                ['id' => '280','src' => 'pirateanimals/croco_legs.png', 'offset' => '0', 'type' => '0','character_id' => '14','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute legs-5'],
                ['id' => '281','src' => 'pirateanimals/croco_eq1_legs.png', 'offset' => '1', 'type' => '0','character_id' => '14','hp' => '5','xp' => '0','gold' => '5','price' => '400', 'classes' => 'is-absolute legs-5'],
                ['id' => '282','src' => 'pirateanimals/croco_eq2_legs.png', 'offset' => '2', 'type' => '0','character_id' => '14','hp' => '15','xp' => '5','gold' => '10','price' => '1000', 'classes' => 'is-absolute legs-5'],
                ['id' => '283','src' => 'pirateanimals/croco_eq3_legs.png', 'offset' => '3', 'type' => '0','character_id' => '14','hp' => '10','xp' => '15','gold' => '20','price' => '800', 'classes' => 'is-absolute legs-5'],
                ['id' => '284','src' => 'pirateanimals/croco_body.png', 'offset' => '0', 'type' => '1','character_id' => '14','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute body-5'],
                ['id' => '285','src' => 'pirateanimals/croco_eq1_body.png', 'offset' => '1', 'type' => '1','character_id' => '14','hp' => '15','xp' => '0','gold' => '5','price' => '700', 'classes' => 'is-absolute body-5'],
                ['id' => '286','src' => 'pirateanimals/croco_eq2_body.png', 'offset' => '2', 'type' => '1','character_id' => '14','hp' => '15','xp' => '10','gold' => '5','price' => '800', 'classes' => 'is-absolute body-5'],
                ['id' => '287','src' => 'pirateanimals/croco_eq3_body.png', 'offset' => '3', 'type' => '1','character_id' => '14','hp' => '10','xp' => '15','gold' => '20','price' => '1200', 'classes' => 'is-absolute body-5'],
                ['id' => '288','src' => 'pirateanimals/croco_head.png', 'offset' => '0', 'type' => '2','character_id' => '14','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'is-absolute head-5 moveHeadUD'],
                ['id' => '289','src' => 'pirateanimals/croco_eq1_head.png', 'offset' => '1', 'type' => '2','character_id' => '14','hp' => '5','xp' => '5','gold' => '0','price' => '400', 'classes' => 'is-absolute head-5 moveHeadUD'],
                ['id' => '290','src' => 'pirateanimals/croco_eq2_head.png', 'offset' => '2', 'type' => '2','character_id' => '14','hp' => '10','xp' => '10','gold' => '10','price' => '800', 'classes' => 'is-absolute head-5 moveHeadUD'],
                ['id' => '291','src' => 'pirateanimals/croco_eq3_head.png', 'offset' => '3', 'type' => '2','character_id' => '14','hp' => '20','xp' => '20','gold' => '40','price' => '1800', 'classes' => 'is-absolute head-5 moveHeadUD'],
                ['id' => '300','src' => 'skeleton_head.png', 'offset' => '0', 'type' => '1','character_id' => '15','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'helmet'],
                ['id' => '301','src' => 'skeleton_body.png', 'offset' => '0', 'type' => '2','character_id' => '15','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'armor'],
                ['id' => '302','src' => 'skeleton_legs.png', 'offset' => '0', 'type' => '3','character_id' => '15','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'boots'],
                ['id' => '303','src' => 'sword-0_974536_char.png', 'offset' => '0', 'type' => '4','character_id' => '15','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'sword'],
                ['id' => '304','src' => 'shield-0_0762db6a6a.png', 'offset' => '0', 'type' => '5','character_id' => '15','hp' => '0','xp' => '0','gold' => '0','price' => '0', 'classes' => 'shield'],
            
                ]
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('character_items');
    }
}
